## Review 15 — verification of the six Review-14 blocking fixes

I checked each at the line level rather than accepting the log. Five of six are genuinely applied; one is applied in the filesystem but not in prose.

**(a) Re-entry bar in the solvability-gate paragraph — SATISFIED.** `mve3-v2-protocol.md:37` now ends: "Re-entering the candidate grid after this solvability gate is evaluated is forbidden without a new protocol, independent review, and human sign-off; disclose the failed bounded grid rather than silently extending or retuning it." That is the paragraph that defines the grid and carries the "record v2 infeasible and stop" clause, so it is the right home. `:57` retains the parallel engagement-gate bar. Note `:55` (the stop clause inside the `## Preregistered development solvability gate` section) still says only "stop and never open pilot or locked-v2 seeds" — non-blocking, since :37 explicitly scopes to "this solvability gate."

**(b) Flat-policy identity test — SATISFIED in substance.** `test_gates.py:15–27` now calls `gates.oracle_none_metrics(cfg, replicates=1)` — the real gate path, not a hand-written array. It patches `gates.auc` with `wraps`, asserts `call_count > 0` (:20), and asserts `analyze.normalized_auc is gates.auc` (:19), which is the shared-usage claim; that identity is real, since `mve3/analyze.py:17` and `mve3v2/gates.py:17` both import from the new `mve3/metrics.py`, and `analyze.py:39–45` is the factorial path. Floats use `assertAlmostEqual` (:23, :24). The added `:24–27` aggregate/per-severity consistency check is a good extra.

Two non-blocking observations. First, the gate's "flat curve" is a *singleton* curve (`gates.py:32`), and `metrics.py:14–15` returns `values[0]` by special case — so the identity is enforced by a length-1 branch rather than by flat-curve trapezoid math. That is fine operationally but is a weaker statement than protocol :39's "the checkpoint curve is flat and this AUC equals its mean." Second, the failure path in `main()` (`gates.py:173`) still writes only `{"candidates": records}` with no identity strings; only `report_only_regenerate` (:147–148) records them. The artifact that exists is fine; a future failure write would not be.

**(c) Regenerated development artifact — SATISFIED.** `development-solvability-failed.json` (19:08, after `gates.py` 19:03) contains `severity_oracle_minus_none_return_auc` for all **27** candidates. The audit is real, not asserted: `pre_existing_metric_fingerprint_sha256` and `regenerated_pre_existing_metric_fingerprint_sha256` are both `0c38a4f4b062…a600bf`, and `report_only_regenerate` (`gates.py:124–138`) raises on count change, ordering change, any per-key metric change, and fingerprint mismatch before writing. Disclosed as report-only in the artifact (`purpose`, :142), `RESULTS.md:3–7`, and `PROGRESS.md:42–48`, each stating no selection, retuning, or new seeds. This also fixes non-blocking item 2: all 27 archived `config` blocks now read `"eval_episodes": 1000`, matching the run.

**(d) Source competence 0.988 — SATISFIED.** `RESULTS.md:29` and `PROGRESS.md:48` both read 0.988. No stale 1.000 remains in v2 scope; the remaining 1.000/1.0 at `PROGRESS.md:131` and `:227` are v1 locked-run figures and correctly untouched.

**(e) Boundary and skipped-timing disclosures — SATISFIED.** `RESULTS.md:38–43` states the best candidate sits at the grid boundary, that oracle success rose with `tau_reference` and clip, and draws the correct conclusion — "not solvable within this preregistered grid," not globally unsolvable — and says extending it now would be outcome-driven. `RESULTS.md:43–46` discloses the skipped costliest-tuple timing pre-check as a protocol deviation with its (correct) argument for harmlessness. Both echoed at `PROGRESS.md:49–50`.

**(f) Pilot rename — DIRECTORY DONE, ONE STALE PROSE REFERENCE REMAINS.** `results/mve3-pilot-v2/` is gone, replaced by `results/mve3-pilot-corrected-v1/`. But **`LEARNINGS.md:33` still reads "Corrected pilot-v2 completed 480/480 cells before the locked decision."** That is the v1 corrected pilot described under its old name, in the most human-facing summary document in the repo. Review-14's own rationale applies here more strongly than to the directory: an auditor grepping `pilot-v2` now finds a *prose assertion that a pilot-v2 ran to completion*, when protocol :29 forbids opening any pilot-v2 seed. Every other surviving `pilot-v2` hit is a legitimate prohibition statement (`mve3-v2-protocol.md:3,29,93`, `RESULTS.md:3`) or the rename note itself (`PROGRESS.md:51`). One-word fix: "Corrected v1 pilot."

Separately non-blocking: `results/mve2-pilot-v2/` exists but is MVE 2, a different experiment predating the v2 tag; no action needed.

**Non-blocking disclosures — both present.** The fifth source-competence guard is disclosed at `RESULTS.md:32–35`, and the code now matches the written four-condition gate (`gates.py:82–85` — competence dropped from `passes_solvability`, retained as a reported metric at :73). The `eval_episodes` misreport is fixed as described in (c).

**PROGRESS.md audit-gap note — PRESENT and appropriately honest.** `PROGRESS.md:5–13` states plainly that the prior claim of full Review-13 application was incomplete, names the three specific gaps, and closes "This is a factual audit gap, not a change to the v2 stop decision." That is the right disclosure and the right scope.

**One caveat on method:** Bash execution was not permitted in this session, so I verified `test_gates.py` by reading it against `gates.py`, `metrics.py`, and `analyze.py`, not by running it. The logic is sound and `PROGRESS.md` records the suite passing; if you want the run independently confirmed, that is a separate check.

The stop decision remains correct and I would not disturb it: no tuple passed, the shortfall at the best candidate is decisive (16.44% vs 25%; 11.36 pp vs 15 pp), the boundary disclosure now makes the honest scope explicit, and `untested — preregistered solvability gate failed` is the right classification.

VERDICT: REVISE — one blocking fix, trivial: correct the stale `pilot-v2` reference at `LEARNINGS.md:33` to name the v1 corrected pilot. With that edit, all six Review-14 items are verified applied and experiments are closed.
